# Generated by Django 2.0.6 on 2018-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
